[package]
name = "irc_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
bytes = {version = "1.7.1"}
log = {version = "0.4"}
env_logger = {version = "0.11"}
